### ISSUE TITLE
A little request about the tool update for 11.4 version of "LOVE"

### ISSUE THREAD

**Issue by JasonNumberThirteen** [Davidobot/love.js#53]
Hi, did you know that "Love2D" in 11.4 version **was released in January**? I'd like to know if you're going to update your tool very soon to grant compatibility with this version (if your tool does not). Can you write something about this?

**Comment by alexjgriffith** [comment]
@Davidobot in the emscripten branches for love and the megasource are any files other than `CmakeLists.txt` altered for compatibility?
