### ISSUE TITLE
issue with something blocking the main thread with love.js build

### ISSUE THREAD

**Issue by lilmike** [Davidobot/love.js#83]
Hiya,

I'm working on making a starter template for blind accessible games made in love2d working on the web, and I'm running into a weird issue where after the game loads, something blocks the main thread of the browser and thus everyything becomes unresponsive. I can't open dev tools to figure out what it is, I can't stop javascript processing, or anything. I'm wondering if you have any idea how I can tell what the heck is blocking the main thread... I actually have three test projects using love.js, only one of them does not hang the browser, and the two modules that are not used in the working one but do exist in the modified version of the working one don't seem to be the culpret, as I totally removed their use from the template and it still froze. If you want to take a look, my code is here: https://git.2mb.codes/~lilmike/love2d-template

Or if you want to look at the website build of the template (it doesn't do much yet, but it will freeze the browser) you can go here: https://2mb.games/love/test/

Thanks for any help, this is starting to drive me crazy lol.

-Michael.

**Comment by lilmike** [comment]
I figured it out.

**Comment by tomcqt** [comment]
What was the issue? I'm having a freeze with a porting project and can't seem to figure it out, so I'm looking at other people's freezes to see if I can find the issue.
